version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 7000:7000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:7000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=potsgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

#  redis:
#    image: redis
#    container_name: redis_container
#
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A Satus worker -l info
#    volumes:
#      - .:/django
#    container_name: celery_container
#    depends_on:
#      - redis
#      - app







