# Generated by Django 4.0.3 on 2022-04-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0002_remove_userprofile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='count',
        ),
        migrations.AlterField(
            model_name='current',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='satus_app.current', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='list',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='satus_app.list', verbose_name='Родитель'),
        ),
    ]
