# Generated by Django 4.0.3 on 2022-04-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0003_remove_userprofile_count_alter_current_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name': 'Current', 'verbose_name_plural': 'Current'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'List', 'verbose_name_plural': 'List'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfile'},
        ),
    ]
