# Generated by Django 4.0.3 on 2022-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0004_alter_current_options_alter_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='photos/2022/04/25/user-default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
