# Generated by Django 4.0.3 on 2022-04-26 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0005_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 4, 27, 30, 25559)),
        ),
        migrations.AlterField(
            model_name='current',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 3, 27, 30, 25559)),
        ),
    ]
