# Generated by Django 4.0.3 on 2022-04-26 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0006_alter_current_end_alter_current_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='current',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
