# Generated by Django 4.0.3 on 2022-04-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satus_app', '0007_alter_current_end_alter_current_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'ordering': ['-start'], 'verbose_name': 'Current', 'verbose_name_plural': 'Current'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-start'], 'verbose_name': 'List', 'verbose_name_plural': 'List'},
        ),
    ]
